### ISSUE TITLE
EXPDAT-013 share product

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#13]
# share product

**As a** user

**I want** to share a product with my friends

**so that** he gets a message (whatsapp, email...) of a product I dont need with name and expiry date

# feature criteria
 - [x] every product in single view #8 has a share button
 - [x] by pressing the share button a windows should appear where I can choose how to send the message.
 - [x] when a messaging service is chosen a standard message like "Hi, I have {PRODUCT_NAME} that I don't need anymore and expires at {EXPIRY_DATE}. Do you want to have it?" should get inserted. The message is editable by the user.

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] tests written for it

**Comment by Zojems08** [comment]
The postitions of the button in the item view(share, delete, close) are not self adapting. So when the language is changed to russian the layout of the buttons is also changed because of the length of the russian words. Maybe we could open a new issue to implement some symbols for these buttons.
![ru_screen](https://user-images.githubusercontent.com/57070587/118406963-aaa4e580-b67e-11eb-9cd1-4b49af8ce7b0.PNG)
